#!/usr/bin/env bash
cd "$(dirname "$(realpath $0)")"

php src/index.php "$@"
EXIT_CODE=$?

if [[ $1 =~ 'toggle' ]]
then
    source .env

    # push if git folder
    if [[ -d "$DATA_PATH/.git" ]]
    then
        cd $DATA_PATH
        skip=. git commit -m 'entry' entries.json
        git push
    fi


fi

exit $EXIT_CODE
