#!/usr/bin/env bash
cd "$(dirname "$(realpath $0)")"

php src/index.php "$@"
EXIT_CODE=$?

if [[ $1 =~ 'toggle' ]]
then
    cd data
    skip=. git commit -m 'entry' entries.json >/dev/null
    git push
fi

exit $EXIT_CODE
